# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 18:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='description email', max_length=254, validators=[django.core.validators.EmailValidator(message='Ingresa un email valido')])),
                ('comentario', models.TextField(default='description default text')),
            ],
        ),
    ]
