# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20170919_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='Catalogo',
        ),
    ]
