# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 02:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170915_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="El formato de telefono es: '+999999999'. maximo 15 digitos permitido.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
