# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 12:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.CharField(default='description address text', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='description email', max_length=254, validators=[django.core.validators.EmailValidator(message='your custom message')]),
        ),
    ]
